### ISSUE TITLE
Create public API controller

### ISSUE THREAD

**Issue by arturjoshi** [irinium/PolicePlatform#2]
We need to implement `/api/v1/` endpoint for serving public API of our service.
In order to test it add `/api/v1/health` **GET** endpoint which returns response status 200 OK with empty body.
See **@RestController @GetMapping** annotations.

**Comment by BohdanKrasko** [comment]
А як його можна перевірити чи правильно і чи це так. Я раніше з цим не працював так що цікаво як має бути
@RestController
public class health {

    @GetMapping()
    public getApplications() {
        return HttpStatus.OK;
    }
